;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(load-file "~/.emacs.local")

;;(load-file "/Melify/private/emacs/common/ruby-mode.el")
;;(load-file "/Melify/private/emacs/common/less.el")
;;(load-file "/Melify/private/emacs/common/mtk.components.el")
;;(load-file "/Melify/private/emacs/common/angular.el")
;;(load-file "/Melify/private/emacs/common/interview.questions.el")
;;(load-file "/Melify/private/emacs/common/interview.IA.el")
;;(load-file "/Melify/private/emacs/common/polymer.el")
;;(load-file "/Melify/private/emacs/common/full-screen.el")
;;(load-file "/Melify/private/emacs/common/tcl-mode.el")

(load-file "/Melify/private/emacs/common/macros.el")
(load-file "/Melify/private/emacs/common/basic.el")
(load-file "/Melify/private/emacs/common/tidy.el")
(load-file "/Melify/private/emacs/common/git.el")
(load-file "/Melify/private/emacs/common/fa.el")
(load-file "/Melify/private/emacs/common/tb.el")
(load-file "/Melify/private/emacs/common/js.el")
(load-file "/Melify/private/emacs/common/html.el")
(load-file "/Melify/private/emacs/common/save.el")
(load-file "/Melify/private/emacs/common/melify-components.el")
(load-file "/Melify/private/emacs/common/web-mode.el")
(load-file "/Melify/private/emacs/common/haml-mode.el")
(load-file "/Melify/private/emacs/common/sass-mode.el")
(load-file "/Melify/private/emacs/common/json.el")
(load-file "/Melify/private/emacs/common/wc.html.el")
(load-file "/Melify/private/emacs/common/wc.js.el")
(load-file "/Melify/private/emacs/common/w3c.el")
(load-file "/Melify/private/emacs/common/yasnippet.el")
